#include "MRVMSystemVariableCatalog.hpp"

#include <algorithm>
#include <cstring>

namespace mrvm_runtime {

struct MRVMSystemVariableEntry {
	const char *name;
	MRVMSystemVariable variable;
};

MRVMSystemVariable classifySystemVariable(const std::string &name) {
	static constexpr MRVMSystemVariableEntry entries[] = {
	    {"AT_EOF", MRVMSystemVariable::AtEof},
	    {"AT_EOL", MRVMSystemVariable::AtEol},
	    {"AUTOSAVE", MRVMSystemVariable::Autosave},
	    {"BACKUPS", MRVMSystemVariable::Backups},
	    {"BACK_COLOR", MRVMSystemVariable::BackColor},
	    {"BLOCK_COL1", MRVMSystemVariable::BlockCol1},
	    {"BLOCK_COL2", MRVMSystemVariable::BlockCol2},
	    {"BLOCK_LINE1", MRVMSystemVariable::BlockLine1},
	    {"BLOCK_LINE2", MRVMSystemVariable::BlockLine2},
	    {"BLOCK_STAT", MRVMSystemVariable::BlockStat},
	    {"BUFFER_ID", MRVMSystemVariable::BufferId},
	    {"CHANGE_COLOR", MRVMSystemVariable::ChangeColor},
	    {"COMSPEC", MRVMSystemVariable::Comspec},
	    {"CPU", MRVMSystemVariable::Cpu},
	    {"CTRL_HELP", MRVMSystemVariable::CtrlHelp},
	    {"CUR_CHAR", MRVMSystemVariable::CurChar},
	    {"CUR_FILE_ATTR", MRVMSystemVariable::CurFileAttr},
	    {"CUR_FILE_SIZE", MRVMSystemVariable::CurFileSize},
	    {"CUR_WINDOW", MRVMSystemVariable::CurWindow},
	    {"CYCLIC_VIRTUAL_DESKTOPS", MRVMSystemVariable::CyclicVirtualDesktops},
	    {"C_COL", MRVMSystemVariable::CCol},
	    {"C_LINE", MRVMSystemVariable::CLine},
	    {"C_PAGE", MRVMSystemVariable::CPage},
	    {"C_ROW", MRVMSystemVariable::CRow},
	    {"DATE", MRVMSystemVariable::Date},
	    {"DEFAULT_FORMAT", MRVMSystemVariable::DefaultFormat},
	    {"DISPLAY_TABS", MRVMSystemVariable::DisplayTabs},
	    {"DOC_MODE", MRVMSystemVariable::DocMode},
	    {"ERROR_COLOR", MRVMSystemVariable::ErrorColor},
	    {"ERROR_LEVEL", MRVMSystemVariable::ErrorLevel},
	    {"EXPLOSIONS", MRVMSystemVariable::Explosions},
	    {"FILE_CHANGED", MRVMSystemVariable::FileChanged},
	    {"FILE_NAME", MRVMSystemVariable::FileName},
	    {"FIRST_MACRO", MRVMSystemVariable::FirstMacro},
	    {"FIRST_RUN", MRVMSystemVariable::FirstRun},
	    {"FIRST_SAVE", MRVMSystemVariable::FirstSave},
	    {"FORMAT_LINE", MRVMSystemVariable::FormatLine},
	    {"FORMAT_RULER", MRVMSystemVariable::FormatRuler},
	    {"FORMAT_STAT", MRVMSystemVariable::FormatStat},
	    {"FOUND_STR", MRVMSystemVariable::FoundStr},
	    {"FOUND_X", MRVMSystemVariable::FoundX},
	    {"FOUND_Y", MRVMSystemVariable::FoundY},
	    {"GET_LINE", MRVMSystemVariable::GetLine},
	    {"IGNORE_CASE", MRVMSystemVariable::IgnoreCase},
	    {"INDENT_LEVEL", MRVMSystemVariable::IndentLevel},
	    {"INDENT_STYLE", MRVMSystemVariable::IndentStyle},
	    {"INSERT_MODE", MRVMSystemVariable::InsertMode},
	    {"INS_CURSOR", MRVMSystemVariable::InsCursor},
	    {"KEY1", MRVMSystemVariable::Key1},
	    {"KEY2", MRVMSystemVariable::Key2},
	    {"LAST_FILE_ATTR", MRVMSystemVariable::LastFileAttr},
	    {"LAST_FILE_NAME", MRVMSystemVariable::LastFileName},
	    {"LAST_FILE_SIZE", MRVMSystemVariable::LastFileSize},
	    {"LAST_FILE_TIME", MRVMSystemVariable::LastFileTime},
	    {"LEFT_MARGIN", MRVMSystemVariable::LeftMargin},
	    {"LINK_STAT", MRVMSystemVariable::LinkStat},
	    {"LOGO_SCREEN", MRVMSystemVariable::LogoScreen},
	    {"MARKING", MRVMSystemVariable::Marking},
	    {"MAX_WINDOW_ROW", MRVMSystemVariable::MaxWindowRow},
	    {"MEM_ALLOC", MRVMSystemVariable::MemAlloc},
	    {"MENU_COLOR", MRVMSystemVariable::MenuColor},
	    {"MESSAGES", MRVMSystemVariable::Messages},
	    {"MESSAGE_ROW", MRVMSystemVariable::MessageRow},
	    {"MIN_WINDOW_ROW", MRVMSystemVariable::MinWindowRow},
	    {"MOUSE", MRVMSystemVariable::Mouse},
	    {"MOUSE_H_SENSE", MRVMSystemVariable::MouseHSense},
	    {"MOUSE_V_SENSE", MRVMSystemVariable::MouseVSense},
	    {"MPARM_STR", MRVMSystemVariable::MparmStr},
	    {"MR_PATH", MRVMSystemVariable::MrPath},
	    {"NAME_LINE", MRVMSystemVariable::NameLine},
	    {"NEXT_MACRO", MRVMSystemVariable::NextMacro},
	    {"OS_VERSION", MRVMSystemVariable::OsVersion},
	    {"OVR_CURSOR", MRVMSystemVariable::OvrCursor},
	    {"PAGE_STR", MRVMSystemVariable::PageStr},
	    {"PARAM_COUNT", MRVMSystemVariable::ParamCount},
	    {"PG_LINE", MRVMSystemVariable::PgLine},
	    {"PRINT_MARGIN", MRVMSystemVariable::PrintMargin},
	    {"READ_ONLY", MRVMSystemVariable::ReadOnly},
	    {"REFRESH", MRVMSystemVariable::Refresh},
	    {"REG_EXP_STAT", MRVMSystemVariable::RegExpStat},
	    {"RETURN_INT", MRVMSystemVariable::ReturnInt},
	    {"RETURN_STR", MRVMSystemVariable::ReturnStr},
	    {"RIGHT_MARGIN", MRVMSystemVariable::RightMargin},
	    {"SEARCH_FILE", MRVMSystemVariable::SearchFile},
	    {"SHADOW_CHAR", MRVMSystemVariable::ShadowChar},
	    {"SHADOW_COLOR", MRVMSystemVariable::ShadowColor},
	    {"STATUS_ROW", MRVMSystemVariable::StatusRow},
	    {"STAT_COLOR", MRVMSystemVariable::StatColor},
	    {"TAB_EXPAND", MRVMSystemVariable::TabExpand},
	    {"TEMP_PATH", MRVMSystemVariable::TempPath},
	    {"TEXT_COLOR", MRVMSystemVariable::TextColor},
	    {"TIME", MRVMSystemVariable::Time},
	    {"TMP_FILE", MRVMSystemVariable::TmpFile},
	    {"TMP_FILE_NAME", MRVMSystemVariable::TmpFileName},
	    {"TRUNCATE_SPACES", MRVMSystemVariable::TruncateSpaces},
	    {"UNDO_STAT", MRVMSystemVariable::UndoStat},
	    {"VIRTUAL_DESKTOPS", MRVMSystemVariable::VirtualDesktops},
	    {"WINDOW_ATTR", MRVMSystemVariable::WindowAttr},
	    {"WINDOW_COUNT", MRVMSystemVariable::WindowCount},
	    {"WIN_X1", MRVMSystemVariable::WinX1},
	    {"WIN_X2", MRVMSystemVariable::WinX2},
	    {"WIN_Y1", MRVMSystemVariable::WinY1},
	    {"WIN_Y2", MRVMSystemVariable::WinY2},
	    {"WORD_DELIMITS", MRVMSystemVariable::WordDelimits},
	    {"WRAP_STAT", MRVMSystemVariable::WrapStat},
	};
	const MRVMSystemVariableEntry *first = entries;
	const MRVMSystemVariableEntry *last = entries + sizeof(entries) / sizeof(entries[0]);
	const MRVMSystemVariableEntry *found = std::lower_bound(first, last, name, [](const MRVMSystemVariableEntry &entry, const std::string &value) { return std::strcmp(entry.name, value.c_str()) < 0; });

	if (found == last || name != found->name) return MRVMSystemVariable::Unknown;
	return found->variable;
}

} // namespace mrvm_runtime
