#include "MRVMProcedureCatalog.hpp"

#include <algorithm>
#include <cstring>

namespace {

struct MRVMProcedureEntry {
	const char *name;
	MRVMProcedure procedure;
};

} // namespace

MRVMProcedure MRVMProcedureCatalog::classify(const std::string &name) {
	static constexpr MRVMProcedureEntry entries[] = {
	    {"ACTIVE_KEYMAP_PROFILE", MRVMProcedure::ActiveKeymapProfile},
	    {"BACK_SPACE", MRVMProcedure::BackSpace},
	    {"BEEP", MRVMProcedure::Beep},
	    {"BLOCK_BEGIN", MRVMProcedure::BlockBegin},
	    {"BLOCK_COL", MRVMProcedure::BlockCol},
	    {"BLOCK_END", MRVMProcedure::BlockEnd},
	    {"BLOCK_LINE", MRVMProcedure::BlockLine},
	    {"BLOCK_OFF", MRVMProcedure::BlockOff},
	    {"BLOCK_STAT", MRVMProcedure::BlockStat},
	    {"BRAIN", MRVMProcedure::Brain},
	    {"CHANGE_DIR", MRVMProcedure::ChangeDir},
	    {"CLEAR_SCREEN", MRVMProcedure::ClearScreen},
	    {"CLR_LINE", MRVMProcedure::ClrLine},
	    {"CMD_TO_KEY", MRVMProcedure::CmdToKey},
	    {"CODECOLORS", MRVMProcedure::CodeColors},
	    {"COL_BLOCK_BEGIN", MRVMProcedure::ColBlockBegin},
	    {"COPY_BLOCK", MRVMProcedure::CopyBlock},
	    {"CR", MRVMProcedure::Cr},
	    {"CREATE_GLOBAL_STR", MRVMProcedure::CreateGlobalStr},
	    {"CREATE_WINDOW", MRVMProcedure::CreateWindow},
	    {"DEBUGGERCOLORS", MRVMProcedure::DebuggerColors},
	    {"DELAY", MRVMProcedure::Delay},
	    {"DELETE_BLOCK", MRVMProcedure::DeleteBlock},
	    {"DELETE_WINDOW", MRVMProcedure::DeleteWindow},
	    {"DEL_CHAR", MRVMProcedure::DelChar},
	    {"DEL_CHARS", MRVMProcedure::DelChars},
	    {"DEL_FILE", MRVMProcedure::DelFile},
	    {"DEL_LINE", MRVMProcedure::DelLine},
	    {"DOWN", MRVMProcedure::Down},
	    {"EOF", MRVMProcedure::Eof},
	    {"EOL", MRVMProcedure::Eol},
	    {"ERASE_WINDOW", MRVMProcedure::EraseWindow},
	    {"EXEC_ASSIGN", MRVMProcedure::ExecAssign},
	    {"EXEC_SESSION_LIST", MRVMProcedure::ExecSessionList},
	    {"EXEC_SESSION_STOP", MRVMProcedure::ExecSessionStop},
	    {"EXPAND_TABS", MRVMProcedure::ExpandTabs},
	    {"EXTEND_BLOCK_BY_MOTION", MRVMProcedure::ExtendBlockByMotion},
	    {"FILECOMPARECOLORS", MRVMProcedure::FileCompareColors},
	    {"FILECOMPAREMINIMAPCOLORS", MRVMProcedure::FileCompareMiniMapColors},
	    {"FIRST_WORD", MRVMProcedure::FirstWord},
	    {"FLABEL", MRVMProcedure::FLabel},
	    {"FORK", MRVMProcedure::Fork},
	    {"GET_RANDOM_MARK", MRVMProcedure::GetRandomMark},
	    {"GOTOXY", MRVMProcedure::GotoXy},
	    {"GOTO_COL", MRVMProcedure::GotoCol},
	    {"GOTO_LINE", MRVMProcedure::GotoLine},
	    {"GOTO_MARK", MRVMProcedure::GotoMark},
	    {"HELPCOLORS", MRVMProcedure::HelpColors},
	    {"HOME", MRVMProcedure::Home},
	    {"INDENT", MRVMProcedure::Indent},
	    {"KEYMAP_BIND", MRVMProcedure::KeymapBind},
	    {"KEYMAP_PROFILE", MRVMProcedure::KeymapProfile},
	    {"KEYMAP_RESET", MRVMProcedure::KeymapReset},
	    {"KEYMAP_VERSION", MRVMProcedure::KeymapVersion},
	    {"KEY_IN", MRVMProcedure::KeyIn},
	    {"KEY_RECORD", MRVMProcedure::KeyRecord},
	    {"KILL_BOX", MRVMProcedure::KillBox},
	    {"LAST_PAGE_BREAK", MRVMProcedure::LastPageBreak},
	    {"LEFT", MRVMProcedure::Left},
	    {"LINK_WINDOW", MRVMProcedure::LinkWindow},
	    {"LOAD_BLOCK", MRVMProcedure::LoadBlock},
	    {"LOAD_FILE", MRVMProcedure::LoadFile},
	    {"LOAD_MACRO_FILE", MRVMProcedure::LoadMacroFile},
	    {"LOAD_WORKSPACE", MRVMProcedure::LoadWorkspace},
	    {"MACRO_TO_KEY", MRVMProcedure::MacroToKey},
	    {"MAKE_MESSAGE", MRVMProcedure::MakeMessage},
	    {"MARK_POS", MRVMProcedure::MarkPos},
	    {"MARQUEE", MRVMProcedure::Marquee},
	    {"MARQUEE_ERROR", MRVMProcedure::MarqueeError},
	    {"MARQUEE_WARNING", MRVMProcedure::MarqueeWarning},
	    {"MENUDIALOGCOLORS", MRVMProcedure::MenuDialogColors},
	    {"MINIMAPCOLORS", MRVMProcedure::MiniMapColors},
	    {"MODIFY_WINDOW", MRVMProcedure::ModifyWindow},
	    {"MOVE_BLOCK", MRVMProcedure::MoveBlock},
	    {"MOVE_VIEWPORT_LEFT", MRVMProcedure::MoveViewportLeft},
	    {"MOVE_VIEWPORT_RIGHT", MRVMProcedure::MoveViewportRight},
	    {"MOVE_WIN_TO_NEXT_DESKTOP", MRVMProcedure::MoveWinToNextDesktop},
	    {"MOVE_WIN_TO_PREV_DESKTOP", MRVMProcedure::MoveWinToPrevDesktop},
	    {"MRCOMPILERPROFILE", MRVMProcedure::MrCompilerProfile},
	    {"MRFEPROFILE", MRVMProcedure::MrFeProfile},
	    {"MRSETUP", MRVMProcedure::MrSetup},
	    {"NEW_SCREEN", MRVMProcedure::NewScreen},
	    {"NEXT_PAGE_BREAK", MRVMProcedure::NextPageBreak},
	    {"OTHERCOLORS", MRVMProcedure::OtherColors},
	    {"PAGE_DOWN", MRVMProcedure::PageDown},
	    {"PAGE_UP", MRVMProcedure::PageUp},
	    {"PASS_KEY", MRVMProcedure::PassKey},
	    {"PLAY_KEY_MACRO", MRVMProcedure::PlayKeyMacro},
	    {"POP_LABELS", MRVMProcedure::PopLabels},
	    {"POP_MARK", MRVMProcedure::PopMark},
	    {"PUSH_KEY", MRVMProcedure::PushKey},
	    {"PUSH_LABELS", MRVMProcedure::PushLabels},
	    {"PUT_BOX", MRVMProcedure::PutBox},
	    {"PUT_COL_NUM", MRVMProcedure::PutColNum},
	    {"PUT_LINE", MRVMProcedure::PutLine},
	    {"PUT_LINE_NUM", MRVMProcedure::PutLineNum},
	    {"QUIT", MRVMProcedure::Quit},
	    {"READ_KEY", MRVMProcedure::ReadKey},
	    {"REDRAW", MRVMProcedure::Redraw},
	    {"REGISTER_MENU_ITEM", MRVMProcedure::RegisterMenuItem},
	    {"REMOVE_MENU_ITEM", MRVMProcedure::RemoveMenuItem},
	    {"REPLACE", MRVMProcedure::Replace},
	    {"REST_OS_SCREEN", MRVMProcedure::RestOsScreen},
	    {"RIGHT", MRVMProcedure::Right},
	    {"RUN_MACRO", MRVMProcedure::RunMacro},
	    {"SAVE_BLOCK", MRVMProcedure::SaveBlock},
	    {"SAVE_FILE", MRVMProcedure::SaveFile},
	    {"SAVE_OS_SCREEN", MRVMProcedure::SaveOsScreen},
	    {"SAVE_SETTINGS", MRVMProcedure::SaveSettings},
	    {"SAVE_WORKSPACE", MRVMProcedure::SaveWorkspace},
	    {"SCROLL_BOX_DN", MRVMProcedure::ScrollBoxDn},
	    {"SCROLL_BOX_UP", MRVMProcedure::ScrollBoxUp},
	    {"SET_CLIPBOARD_TEXT", MRVMProcedure::SetClipboardText},
	    {"SET_FILE_ATTR", MRVMProcedure::SetFileAttr},
	    {"SET_GLOBAL_HASH", MRVMProcedure::SetGlobalHash},
	    {"SET_GLOBAL_INT", MRVMProcedure::SetGlobalInt},
	    {"SET_GLOBAL_STR", MRVMProcedure::SetGlobalStr},
	    {"SET_INDENT_LEVEL", MRVMProcedure::SetIndentLevel},
	    {"SET_RANDOM_MARK", MRVMProcedure::SetRandomMark},
	    {"SHELL_TO_OS", MRVMProcedure::ShellToOs},
	    {"SIZE_WINDOW", MRVMProcedure::SizeWindow},
	    {"STR_BLOCK_BEGIN", MRVMProcedure::StrBlockBegin},
	    {"SWITCH_WINDOW", MRVMProcedure::SwitchWindow},
	    {"TABS_TO_SPACES", MRVMProcedure::TabsToSpaces},
	    {"TAB_LEFT", MRVMProcedure::TabLeft},
	    {"TAB_RIGHT", MRVMProcedure::TabRight},
	    {"TEXT", MRVMProcedure::Text},
	    {"THEME_NAME", MRVMProcedure::ThemeName},
	    {"THEME_RESET", MRVMProcedure::ThemeReset},
	    {"THEME_VERSION", MRVMProcedure::ThemeVersion},
	    {"TOF", MRVMProcedure::Tof},
	    {"UI_BUTTON", MRVMProcedure::UiButton},
	    {"UI_DIALOG", MRVMProcedure::UiDialog},
	    {"UI_DISPLAY", MRVMProcedure::UiDisplay},
	    {"UI_GRID", MRVMProcedure::UiGrid},
	    {"UI_INPUT", MRVMProcedure::UiInput},
	    {"UI_LABEL", MRVMProcedure::UiLabel},
	    {"UI_LISTBOX", MRVMProcedure::UiListBox},
	    {"UI_LIST_ADD", MRVMProcedure::UiListAdd},
	    {"UI_LIST_CLEAR", MRVMProcedure::UiListClear},
	    {"UI_MESSAGEBOX", MRVMProcedure::UiMessageBox},
	    {"UI_MODELESS_CLOSE", MRVMProcedure::UiModelessClose},
	    {"UI_MODELESS_DISPLAY", MRVMProcedure::UiModelessDisplay},
	    {"UI_MODELESS_ON", MRVMProcedure::UiModelessOn},
	    {"UI_MODELESS_SHOW", MRVMProcedure::UiModelessShow},
	    {"UI_MODELESS_UPDATE", MRVMProcedure::UiModelessUpdate},
	    {"UI_TABLE", MRVMProcedure::UiTable},
	    {"UI_TABLE_CLEAR", MRVMProcedure::UiTableClear},
	    {"UI_TABLE_COLUMN", MRVMProcedure::UiTableColumn},
	    {"UI_TABLE_ROW", MRVMProcedure::UiTableRow},
	    {"UI_TREE", MRVMProcedure::UiTree},
	    {"UI_TREE_CLEAR", MRVMProcedure::UiTreeClear},
	    {"UI_TREE_NODE", MRVMProcedure::UiTreeNode},
	    {"UNASSIGN_ALL_KEYS", MRVMProcedure::UnassignAllKeys},
	    {"UNASSIGN_KEY", MRVMProcedure::UnassignKey},
	    {"UNDENT", MRVMProcedure::Undent},
	    {"UNLINK_WINDOW", MRVMProcedure::UnlinkWindow},
	    {"UNLOAD_MACRO", MRVMProcedure::UnloadMacro},
	    {"UP", MRVMProcedure::Up},
	    {"WINDOWCOLORS", MRVMProcedure::WindowColors},
	    {"WINDOW_COPY", MRVMProcedure::WindowCopy},
	    {"WINDOW_MOVE", MRVMProcedure::WindowMove},
	    {"WORD_LEFT", MRVMProcedure::WordLeft},
	    {"WORD_RIGHT", MRVMProcedure::WordRight},
	    {"WORD_WRAP_LINE", MRVMProcedure::WordWrapLine},
	    {"WORKING", MRVMProcedure::Working},
	    {"WRITE", MRVMProcedure::Write},
	    {"WRITE_SOD", MRVMProcedure::WriteSod},
	    {"ZOOM", MRVMProcedure::Zoom},
	};
	const MRVMProcedureEntry *first = entries;
	const MRVMProcedureEntry *last = entries + sizeof(entries) / sizeof(entries[0]);
	const MRVMProcedureEntry *found = std::lower_bound(first, last, name, [](const MRVMProcedureEntry &entry, const std::string &value) { return std::strcmp(entry.name, value.c_str()) < 0; });

	if (found == last || name != found->name) return MRVMProcedure::Unknown;
	return found->procedure;
}

MRVMProcedureCatalog::Family MRVMProcedureCatalog::family(Procedure procedure) {
	switch (procedure) {
		case MRVMProcedure::ExecAssign:
		case MRVMProcedure::KeymapReset:
		case MRVMProcedure::KeymapVersion:
		case MRVMProcedure::ThemeVersion:
		case MRVMProcedure::KeymapProfile:
		case MRVMProcedure::KeymapBind:
		case MRVMProcedure::ActiveKeymapProfile:
		case MRVMProcedure::ThemeReset:
		case MRVMProcedure::ThemeName:
		case MRVMProcedure::WindowColors:
		case MRVMProcedure::MenuDialogColors:
		case MRVMProcedure::HelpColors:
		case MRVMProcedure::OtherColors:
		case MRVMProcedure::MiniMapColors:
		case MRVMProcedure::FileCompareMiniMapColors:
		case MRVMProcedure::CodeColors:
		case MRVMProcedure::FileCompareColors:
		case MRVMProcedure::DebuggerColors:
		case MRVMProcedure::MrSetup:
		case MRVMProcedure::MrFeProfile:
		case MRVMProcedure::MrCompilerProfile:
		case MRVMProcedure::UiDialog:
		case MRVMProcedure::UiLabel:
		case MRVMProcedure::UiButton:
		case MRVMProcedure::UiDisplay:
		case MRVMProcedure::UiInput:
		case MRVMProcedure::UiListBox:
		case MRVMProcedure::UiGrid:
		case MRVMProcedure::UiTree:
		case MRVMProcedure::UiTreeClear:
		case MRVMProcedure::UiTreeNode:
		case MRVMProcedure::UiTable:
		case MRVMProcedure::UiTableClear:
		case MRVMProcedure::UiTableColumn:
		case MRVMProcedure::UiTableRow:
		case MRVMProcedure::UiListClear:
		case MRVMProcedure::UiListAdd:
		case MRVMProcedure::UiModelessOn:
		case MRVMProcedure::UiModelessShow:
		case MRVMProcedure::UiModelessUpdate:
		case MRVMProcedure::UiModelessDisplay:
		case MRVMProcedure::UiModelessClose:
		case MRVMProcedure::ExecSessionList:
		case MRVMProcedure::ExecSessionStop:
		case MRVMProcedure::CreateGlobalStr:
		case MRVMProcedure::SetGlobalStr:
		case MRVMProcedure::SetGlobalInt:
		case MRVMProcedure::SetGlobalHash:
		case MRVMProcedure::Marquee:
		case MRVMProcedure::MarqueeWarning:
		case MRVMProcedure::MarqueeError:
		case MRVMProcedure::MakeMessage:
		case MRVMProcedure::UiMessageBox:
		case MRVMProcedure::Working:
		case MRVMProcedure::Brain:
		case MRVMProcedure::PutBox:
		case MRVMProcedure::Write:
		case MRVMProcedure::ClrLine:
		case MRVMProcedure::GotoXy:
		case MRVMProcedure::PutLineNum:
		case MRVMProcedure::PutColNum:
		case MRVMProcedure::ScrollBoxUp:
		case MRVMProcedure::ScrollBoxDn:
		case MRVMProcedure::ClearScreen:
		case MRVMProcedure::KillBox:
		case MRVMProcedure::RegisterMenuItem:
		case MRVMProcedure::RemoveMenuItem:
			return Family::Configuration;
		case MRVMProcedure::Delay:
		case MRVMProcedure::Beep:
		case MRVMProcedure::LoadMacroFile:
		case MRVMProcedure::UnloadMacro:
		case MRVMProcedure::ChangeDir:
		case MRVMProcedure::DelFile:
		case MRVMProcedure::SetFileAttr:
		case MRVMProcedure::ShellToOs:
		case MRVMProcedure::Fork:
		case MRVMProcedure::WriteSod:
		case MRVMProcedure::SaveOsScreen:
		case MRVMProcedure::RestOsScreen:
		case MRVMProcedure::Quit:
		case MRVMProcedure::LoadFile:
		case MRVMProcedure::LoadBlock:
		case MRVMProcedure::SaveFile:
		case MRVMProcedure::SaveBlock:
		case MRVMProcedure::SetIndentLevel:
		case MRVMProcedure::Replace:
		case MRVMProcedure::Text:
		case MRVMProcedure::SetClipboardText:
		case MRVMProcedure::KeyIn:
		case MRVMProcedure::ReadKey:
		case MRVMProcedure::PushKey:
		case MRVMProcedure::PassKey:
		case MRVMProcedure::PushLabels:
		case MRVMProcedure::PopLabels:
		case MRVMProcedure::FLabel:
		case MRVMProcedure::MacroToKey:
		case MRVMProcedure::CmdToKey:
		case MRVMProcedure::UnassignKey:
		case MRVMProcedure::UnassignAllKeys:
		case MRVMProcedure::KeyRecord:
		case MRVMProcedure::PlayKeyMacro:
			return Family::Runtime;
		case MRVMProcedure::PutLine:
		case MRVMProcedure::Cr:
		case MRVMProcedure::DelChar:
		case MRVMProcedure::DelChars:
		case MRVMProcedure::DelLine:
		case MRVMProcedure::BackSpace:
		case MRVMProcedure::WordWrapLine:
		case MRVMProcedure::SetRandomMark:
		case MRVMProcedure::GetRandomMark:
		case MRVMProcedure::ExtendBlockByMotion:
		case MRVMProcedure::Left:
		case MRVMProcedure::Right:
		case MRVMProcedure::Up:
		case MRVMProcedure::Down:
		case MRVMProcedure::Home:
		case MRVMProcedure::Eol:
		case MRVMProcedure::Tof:
		case MRVMProcedure::Eof:
		case MRVMProcedure::WordLeft:
		case MRVMProcedure::WordRight:
		case MRVMProcedure::FirstWord:
		case MRVMProcedure::MarkPos:
		case MRVMProcedure::GotoMark:
		case MRVMProcedure::PopMark:
		case MRVMProcedure::PageUp:
		case MRVMProcedure::PageDown:
		case MRVMProcedure::NextPageBreak:
		case MRVMProcedure::LastPageBreak:
		case MRVMProcedure::TabRight:
		case MRVMProcedure::TabLeft:
		case MRVMProcedure::Indent:
		case MRVMProcedure::Undent:
		case MRVMProcedure::BlockBegin:
		case MRVMProcedure::BlockLine:
		case MRVMProcedure::ColBlockBegin:
		case MRVMProcedure::BlockCol:
		case MRVMProcedure::StrBlockBegin:
		case MRVMProcedure::BlockEnd:
		case MRVMProcedure::BlockOff:
		case MRVMProcedure::BlockToggleVisibility:
		case MRVMProcedure::BlockStat:
		case MRVMProcedure::CopyBlock:
		case MRVMProcedure::MoveBlock:
		case MRVMProcedure::DeleteBlock:
		case MRVMProcedure::CreateWindow:
		case MRVMProcedure::DeleteWindow:
		case MRVMProcedure::EraseWindow:
		case MRVMProcedure::ModifyWindow:
		case MRVMProcedure::LinkWindow:
		case MRVMProcedure::UnlinkWindow:
		case MRVMProcedure::Zoom:
		case MRVMProcedure::Redraw:
		case MRVMProcedure::NewScreen:
		case MRVMProcedure::MoveWinToNextDesktop:
		case MRVMProcedure::MoveWinToPrevDesktop:
		case MRVMProcedure::MoveViewportRight:
		case MRVMProcedure::MoveViewportLeft:
		case MRVMProcedure::SaveWorkspace:
		case MRVMProcedure::LoadWorkspace:
		case MRVMProcedure::SaveSettings:
		case MRVMProcedure::GotoLine:
		case MRVMProcedure::GotoCol:
		case MRVMProcedure::SwitchWindow:
		case MRVMProcedure::SizeWindow:
		case MRVMProcedure::WindowCopy:
		case MRVMProcedure::WindowMove:
			return Family::Editor;
		case MRVMProcedure::RunMacro:
		case MRVMProcedure::ExpandTabs:
		case MRVMProcedure::TabsToSpaces:
		case MRVMProcedure::Unknown:
			return Family::Macro;
	}
	return Family::Macro;
}
