#define Uses_TApplication
#define Uses_TDeskTop
#define Uses_TDialog
#define Uses_MsgBox
#define Uses_TObject
#define Uses_TButton
#define Uses_TInputLine
#define Uses_TRect
#define Uses_TStaticText
#include <tvision/tv.h>

#include "MRSetupDialogs.hpp"

#include "../app/MRCommands.hpp"
#include "../app/TMREditorApp.hpp"
#include "../services/MRDialogPaths.hpp"
#include "../ui/MRWindowSupport.hpp"
#include "MRSetupDialogCommon.hpp"

#include <cerrno>
#include <cctype>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <string>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <vector>

namespace {
enum : ushort {
	cmMrSetupPathsHelp = 3800
};

enum {
	kPathFieldSize = 256
};

struct PathsDialogRecord {
	char settingsMacroPath[kPathFieldSize];
	char macroDirectoryPath[kPathFieldSize];
	char helpFilePath[kPathFieldSize];
	char tempDirectoryPath[kPathFieldSize];
	char shellExecutablePath[kPathFieldSize];
};

std::string trimAscii(const std::string &value) {
	std::size_t start = 0;
	std::size_t end = value.size();

	while (start < end && std::isspace(static_cast<unsigned char>(value[start])) != 0)
		++start;
	while (end > start && std::isspace(static_cast<unsigned char>(value[end - 1])) != 0)
		--end;
	return value.substr(start, end - start);
}

std::string readRecordField(const char *value) {
	return trimAscii(value != nullptr ? value : "");
}

void writeRecordField(char *dest, std::size_t destSize, const std::string &value) {
	if (dest == nullptr || destSize == 0)
		return;
	std::memset(dest, 0, destSize);
	std::strncpy(dest, value.c_str(), destSize - 1);
	dest[destSize - 1] = '\0';
}

bool recordsEqual(const PathsDialogRecord &lhs, const PathsDialogRecord &rhs) {
	return readRecordField(lhs.settingsMacroPath) == readRecordField(rhs.settingsMacroPath) &&
	       readRecordField(lhs.macroDirectoryPath) == readRecordField(rhs.macroDirectoryPath) &&
	       readRecordField(lhs.helpFilePath) == readRecordField(rhs.helpFilePath) &&
	       readRecordField(lhs.tempDirectoryPath) == readRecordField(rhs.tempDirectoryPath) &&
	       readRecordField(lhs.shellExecutablePath) == readRecordField(rhs.shellExecutablePath);
}

std::string directoryPartOf(const std::string &path) {
	std::size_t pos;
	if (path.empty())
		return std::string();
	pos = path.find_last_of('/');
	if (pos == std::string::npos)
		return std::string();
	if (pos == 0)
		return "/";
	return path.substr(0, pos);
}

bool ensureDirectoryTree(const std::string &directoryPath, std::string &errorText) {
	struct stat st;
	std::string parentPath;

	if (directoryPath.empty() || directoryPath == "." || directoryPath == "/") {
		errorText.clear();
		return true;
	}
	if (::stat(directoryPath.c_str(), &st) == 0) {
		if (S_ISDIR(st.st_mode)) {
			errorText.clear();
			return true;
		}
		errorText = "Path exists and is not a directory: " + directoryPath;
		return false;
	}
	parentPath = directoryPartOf(directoryPath);
	if (!parentPath.empty() && parentPath != directoryPath)
		if (!ensureDirectoryTree(parentPath, errorText))
			return false;
	if (::mkdir(directoryPath.c_str(), 0755) != 0 && errno != EEXIST) {
		errorText = "Unable to create directory: " + directoryPath;
		return false;
	}
	errorText.clear();
	return true;
}

bool writeTextFile(const std::string &path, const std::string &content) {
	std::ofstream out(path.c_str(), std::ios::out | std::ios::binary | std::ios::trunc);
	if (!out)
		return false;
	out << content;
	return out.good();
}

std::string escapeMrmacStringLiteral(const std::string &value) {
	std::string out;
	out.reserve(value.size() + 8);
	for (std::size_t i = 0; i < value.size(); ++i) {
		char ch = value[i];
		switch (ch) {
			case '\\':
				out += "\\\\";
				break;
			case '"':
				out += "\\\"";
				break;
			case '\n':
				out += "\\n";
				break;
			case '\r':
				out += "\\r";
				break;
			case '\t':
				out += "\\t";
				break;
			default:
				out.push_back(ch);
				break;
		}
	}
	return out;
}

std::string buildPathsSettingsMacroSource(const PathsDialogRecord &record) {
	std::string settingsPath = normalizeConfiguredPathInput(readRecordField(record.settingsMacroPath));
	std::string macroDir = normalizeConfiguredPathInput(readRecordField(record.macroDirectoryPath));
	std::string helpPath = normalizeConfiguredPathInput(readRecordField(record.helpFilePath));
	std::string tempDir = normalizeConfiguredPathInput(readRecordField(record.tempDirectoryPath));
	std::string shellPath = normalizeConfiguredPathInput(readRecordField(record.shellExecutablePath));
	std::string source;

	source += "$MACRO MR_SETTINGS FROM EDIT;\n";
	source += "; Auto-generated by Installation / Paths dialog.\n";
	source += "MRSETUP(\"SETTINGSPATH\", \"" + escapeMrmacStringLiteral(settingsPath) + "\");\n";
	source += "MRSETUP(\"MACROPATH\", \"" + escapeMrmacStringLiteral(macroDir) + "\");\n";
	source += "MRSETUP(\"HELPPATH\", \"" + escapeMrmacStringLiteral(helpPath) + "\");\n";
	source += "MRSETUP(\"TEMPDIR\", \"" + escapeMrmacStringLiteral(tempDir) + "\");\n";
	source += "MRSETUP(\"SHELLPATH\", \"" + escapeMrmacStringLiteral(shellPath) + "\");\n";
	source += "END_MACRO;\n";
	return source;
}

void initPathsDialogRecord(PathsDialogRecord &record) {
	std::memset(&record, 0, sizeof(record));
	writeRecordField(record.settingsMacroPath, sizeof(record.settingsMacroPath), configuredSettingsMacroFilePath());
	writeRecordField(record.macroDirectoryPath, sizeof(record.macroDirectoryPath), defaultMacroDirectoryPath());
	writeRecordField(record.helpFilePath, sizeof(record.helpFilePath), configuredHelpFilePath());
	writeRecordField(record.tempDirectoryPath, sizeof(record.tempDirectoryPath), configuredTempDirectoryPath());
	writeRecordField(record.shellExecutablePath, sizeof(record.shellExecutablePath), configuredShellExecutablePath());
}

bool validatePathsRecord(const PathsDialogRecord &record, std::string &errorText) {
	std::string settingsPath = normalizeConfiguredPathInput(readRecordField(record.settingsMacroPath));
	std::string macroDir = normalizeConfiguredPathInput(readRecordField(record.macroDirectoryPath));
	std::string helpPath = normalizeConfiguredPathInput(readRecordField(record.helpFilePath));
	std::string tempDir = normalizeConfiguredPathInput(readRecordField(record.tempDirectoryPath));
	std::string shellPath = normalizeConfiguredPathInput(readRecordField(record.shellExecutablePath));

	if (!validateSettingsMacroFilePath(settingsPath, &errorText))
		return false;
	if (!validateMacroDirectoryPath(macroDir, &errorText))
		return false;
	if (!validateHelpFilePath(helpPath, &errorText))
		return false;
	if (!validateTempDirectoryPath(tempDir, &errorText))
		return false;
	if (!validateShellExecutablePath(shellPath, &errorText))
		return false;
	errorText.clear();
	return true;
}

bool saveAndReloadPathsRecord(const PathsDialogRecord &record, std::string &errorText) {
	std::string settingsPath = normalizeConfiguredPathInput(readRecordField(record.settingsMacroPath));
	std::string settingsDir = directoryPartOf(settingsPath);
	std::string source;
	TMREditorApp *app;

	if (!validatePathsRecord(record, errorText))
		return false;
	if (!ensureDirectoryTree(settingsDir, errorText))
		return false;

	source = buildPathsSettingsMacroSource(record);
	if (!writeTextFile(settingsPath, source)) {
		errorText = "Unable to write settings macro file: " + settingsPath;
		return false;
	}

	app = dynamic_cast<TMREditorApp *>(TProgram::application);
	if (app == nullptr) {
		errorText = "Application error: TMREditorApp is unavailable.";
		return false;
	}
	if (!app->reloadSettingsMacroFromPath(settingsPath, &errorText))
		return false;

	errorText.clear();
	return true;
}

ushort execDialogRaw(TDialog *dialog) {
	ushort result = cmCancel;
	if (dialog != 0) {
		result = TProgram::deskTop->execView(dialog);
		TObject::destroy(dialog);
	}
	return result;
}

ushort execDialog(TDialog *dialog) {
	ushort result = execDialogRaw(dialog);
	if (result == cmHelp)
		mrShowProjectHelp();
	return result;
}

class TPathsSetupDialog : public TDialog {
  public:
	explicit TPathsSetupDialog(const PathsDialogRecord &initialRecord)
	    : TWindowInit(&TDialog::initFrame), TDialog(centeredSetupDialogRect(78, 22), "PATHS"),
	      initialRecord_(initialRecord), currentRecord_(initialRecord) {
		insert(new TStaticText(TRect(2, 2, 76, 3), "Settings macro URI (path + filename):"));
		insert(new TInputLine(TRect(2, 3, 76, 4), kPathFieldSize - 1));

		insert(new TStaticText(TRect(2, 5, 76, 6), "Macro directory path (*.mrmac):"));
		insert(new TInputLine(TRect(2, 6, 76, 7), kPathFieldSize - 1));

		insert(new TStaticText(TRect(2, 8, 76, 9), "Help file path/URI:"));
		insert(new TInputLine(TRect(2, 9, 76, 10), kPathFieldSize - 1));

		insert(new TStaticText(TRect(2, 11, 76, 12), "Temporary directory path:"));
		insert(new TInputLine(TRect(2, 12, 76, 13), kPathFieldSize - 1));

		insert(new TStaticText(TRect(2, 14, 76, 15), "Shell executable path:"));
		insert(new TInputLine(TRect(2, 15, 76, 16), kPathFieldSize - 1));

		insert(new TButton(TRect(44, 19, 54, 21), "Done", cmOK, bfDefault));
		insert(new TButton(TRect(56, 19, 68, 21), "Cancel", cmCancel, bfNormal));
		insert(new TButton(TRect(69, 19, 76, 21), "Help", cmMrSetupPathsHelp, bfNormal));

		setData(&currentRecord_);
	}

	ushort run(PathsDialogRecord &outRecord, bool &changed) {
		ushort result = TProgram::deskTop->execView(this);
		getData(&currentRecord_);
		outRecord = currentRecord_;
		changed = !recordsEqual(initialRecord_, currentRecord_);
		return result;
	}

  private:
	PathsDialogRecord initialRecord_;
	PathsDialogRecord currentRecord_;
};

void showPathsHelpDummyDialog() {
	std::vector<std::string> lines;
	lines.push_back("PATHS HELP");
	lines.push_back("");
	lines.push_back("Dummy help screen.");
	lines.push_back("Configure settings URI, macro path, help file, temp path and shell.");
	lines.push_back("Done saves settings.mrmac and reloads silently.");
	lines.push_back("Cancel asks for confirmation when fields were modified.");
	execDialog(createSetupSimplePreviewDialog("PATHS HELP", 70, 14, lines, false));
}

void runPathsSetupDialogFlowLocal() {
	bool running = true;
	PathsDialogRecord workingRecord;
	std::string errorText;

	initPathsDialogRecord(workingRecord);
	while (running) {
		ushort result;
		bool changed = false;
		PathsDialogRecord editedRecord = workingRecord;
		TPathsSetupDialog *dialog = new TPathsSetupDialog(workingRecord);

		if (dialog == nullptr)
			return;
		result = dialog->run(editedRecord, changed);
		TObject::destroy(dialog);
		workingRecord = editedRecord;

		switch (result) {
			case cmMrSetupPathsHelp:
				showPathsHelpDummyDialog();
				break;

			case cmOK:
				if (!saveAndReloadPathsRecord(workingRecord, errorText)) {
					messageBox(mfError | mfOKButton, "Installation / Paths\n\n%s", errorText.c_str());
					break;
				}
				running = false;
				break;

			case cmCancel:
				if (changed) {
					if (messageBox(mfConfirmation | mfYesButton | mfNoButton,
					               "Discard changed path settings?") != cmYes)
						break;
				}
				running = false;
				break;

			default:
				running = false;
				break;
		}
	}
}
} // namespace

void runColorSetupDialogFlowLocal() {
	bool running = true;

	while (running) {
		ushort result = execDialog(createColorSetupDialog());
		switch (result) {
			case cmMrColorWindowColors:
				execDialog(createWindowColorsDialog());
				break;

			case cmMrColorMenuDialogColors:
				execDialog(createMenuDialogColorsDialog());
				break;

			case cmMrColorHelpColors:
				execDialog(createHelpColorsDialog());
				break;

			case cmMrColorOtherColors:
				execDialog(createOtherColorsDialog());
				break;

			case cmCancel:
			default:
				running = false;
				break;
		}
	}
}

void runInstallationAndSetupDialogFlow() {
	bool running = true;

	while (running) {
		ushort result = execDialog(createInstallationAndSetupDialog());
		switch (result) {
			case cmMrSetupEditSettings:
				execDialog(createEditSettingsDialog());
				break;

			case cmMrSetupDisplaySetup:
				execDialog(createDisplaySetupDialog());
				break;

			case cmMrSetupColorSetup:
				runColorSetupDialogFlowLocal();
				break;

			case cmMrSetupSwappingEmsXms:
				runPathsSetupDialogFlowLocal();
				break;

			case cmMrSetupSearchAndReplaceDefaults:
				messageBox(mfInformation | mfOKButton,
				           "Installation / Search and Replace defaults\n\nDummy implementation for now.");
				break;

			case cmMrSetupSaveConfigurationAndExit:
				messageBox(mfInformation | mfOKButton,
				           "Installation / Save configuration and exit\n\nDummy implementation for now.");
				running = false;
				break;

			case cmCancel:
			default:
				running = false;
				break;
		}
	}
}
