#ifndef MRCOMMANDS_HPP
#define MRCOMMANDS_HPP

#include <tvision/tv.h>

enum : ushort {
	cmMrFileOpen = 110,
	cmMrFileLoad,
	cmMrFileSave,
	cmMrFileSaveAs,
	cmMrFileInformation,
	cmMrFileMerge,
	cmMrFilePrint,
	cmMrFileShellToDos,

	cmMrEditUndo,
	cmMrEditCutToBuffer,
	cmMrEditCopyToBuffer,
	cmMrEditAppendToBuffer,
	cmMrEditCutAndAppendToBuffer,
	cmMrEditPasteFromBuffer,
	cmMrEditRepeatCommand,

	cmMrWindowOpen,
	cmMrWindowClose,
	cmMrWindowSplit,
	cmMrWindowList,
	cmMrWindowNext,
	cmMrWindowPrevious,
	cmMrWindowAdjacent,
	cmMrWindowHide,
	cmMrWindowModifySize,
	cmMrWindowZoom,
	cmMrWindowMinimize,
	cmMrWindowOrganize,
	cmMrWindowLink,
	cmMrWindowUnlink,
	cmMrWindowOrganizePlaceholder,

	cmMrBlockCopy,
	cmMrBlockMove,
	cmMrBlockDelete,
	cmMrBlockSaveToDisk,
	cmMrBlockIndent,
	cmMrBlockUndent,
	cmMrBlockWindowCopy,
	cmMrBlockWindowMove,
	cmMrBlockMarkLines,
	cmMrBlockMarkColumns,
	cmMrBlockMarkStream,
	cmMrBlockEndMarking,
	cmMrBlockTurnMarkingOff,
	cmMrBlockPersistent,

	cmMrSearchFindText,
	cmMrSearchReplace,
	cmMrSearchRepeatPrevious,
	cmMrSearchPushMarker,
	cmMrSearchGetMarker,
	cmMrSearchSetRandomAccessMark,
	cmMrSearchRetrieveRandomAccessMark,
	cmMrSearchGotoLineNumber,

	cmMrTextLayout,
	cmMrTextUpperCaseMenu,
	cmMrTextLowerCaseMenu,
	cmMrTextCenterLine,
	cmMrTextTimeDateStamp,
	cmMrTextReformatParagraph,
	cmMrTextUpperCasePlaceholder,
	cmMrTextLowerCasePlaceholder,

	cmMrOtherInstallationAndSetup,
	cmMrOtherKeystrokeMacros,
	cmMrOtherExecuteProgram,
	cmMrOtherStopProgram,
	cmMrOtherRestartProgram,
	cmMrOtherClearOutput,
	cmMrOtherFindNextCompilerError,
	cmMrOtherMatchBraceOrParen,
	cmMrOtherAsciiTable,

	cmMrMacroToggleRecording,

	cmMrHelpContents,
	cmMrHelpKeys,
	cmMrHelpDetailedIndex,
	cmMrHelpPreviousTopic,
	cmMrHelpAbout,

	cmMrSetupEditSettings,
	cmMrSetupDisplaySetup,
	cmMrSetupColorSetup,
	cmMrSetupKeyMapping,
	cmMrSetupMouseKeyRepeat,
	cmMrSetupFilenameExtensions,
	cmMrSetupSwappingEmsXms,
	cmMrSetupBackupsTempAutosave,
	cmMrSetupSearchAndReplaceDefaults,
	cmMrSetupUserInterfaceSettings,
	cmMrSetupSaveConfigurationAndExit,
	cmMrSetupSearchAndReplacePlaceholder,

	cmMrColorWindowColors,
	cmMrColorMenuDialogColors,
	cmMrColorHelpColors,
	cmMrColorOtherColors,

	cmMrDevRunMacro,
	cmMrDevCancelMacroTasks,
	cmMrPreviewPrev,
	cmMrPreviewNext
};

#endif
