#ifndef MRCOMMANDS_HPP
#define MRCOMMANDS_HPP

#include <tvision/tv.h>

enum : ushort {
	cmMrDebuggerStart = 109,
	cmMrFileOpen = 110,
	cmMrFileLoad,
	cmMrFileAcquire,
	cmMrFileOpenLiveLog,
	cmMrFileOpenJournal,
	cmMrFileSave,
	cmMrFileSaveAs,
	cmMrFileInformation,
	cmMrFileMerge,
	cmMrFilePrint,
	cmMrFileShellToDos,

	cmMrEditUndo,
	cmMrEditRedo,
	cmMrEditMarkAll,
	cmMrEditCutToBuffer,
	cmMrEditCopyToBuffer,
	cmMrEditAppendToBuffer,
	cmMrEditCutAndAppendToBuffer,
	cmMrEditPasteFromBuffer,
	cmMrEditRepeatCommand,

	cmMrWindowOpen,
	cmMrWindowClose,
	cmMrWindowSplit,
	cmMrWindowList,
	cmMrWindowNext,
	cmMrWindowPrevious,
	cmMrWindowAdjacent,
	cmMrWindowHide,
	cmMrWindowModifySize,
	cmMrWindowZoom,
	cmMrWindowMinimize,
	cmMrWindowRestore,
	cmMrWindowOrganize,
	cmMrWindowLink,
	cmMrWindowUnlink,
	cmMrWindowCascade,
	cmMrWindowTile,
	cmMrWindowSplitHorizontal,
	cmMrWindowSplitVertical,
	cmMrWindowNextDesktop,
	cmMrWindowPrevDesktop,
	cmMrWindowMoveToNextDesktop,
	cmMrWindowMoveToPrevDesktop,

	cmMrBlockCopy,
	cmMrBlockMove,
	cmMrBlockDelete,
	cmMrBlockSaveToDisk,
	cmMrBlockIndent,
	cmMrBlockUndent,
	cmMrBlockWindowCopy,
	cmMrBlockWindowMove,
	cmMrBlockMarkLines,
	cmMrBlockMarkColumns,
	cmMrBlockMarkStream,
	cmMrBlockToggleMarking,
	cmMrBlockToggleVisibility,
	cmMrBlockEndMarking,
	cmMrBlockTurnMarkingOff,
	cmMrBlockPersistent,

	cmMrSearchFindText,
	cmMrSearchReplace,
	cmMrSearchRepeatPrevious,
	cmMrSearchPushMarker,
	cmMrSearchGetMarker,
	cmMrSearchSetRandomAccessMark,
	cmMrSearchRetrieveRandomAccessMark,
	cmMrSearchGotoLineNumber,

	cmMrTextLayout,
	cmMrTextUpperCaseMenu,
	cmMrTextLowerCaseMenu,
	cmMrTextCenterLine,
	cmMrTextTimeDateStamp,
	cmMrTextReformatParagraph,
	cmMrTextPrettifyBlockOrFile,
	cmMrTextFileCompare,
	cmMrTextUpperCasePlaceholder,
	cmMrTextLowerCasePlaceholder,

	cmMrSetupMenu,
	cmMrMacroLibrary,
	cmMrDebugExecuteProgram,
	cmMrDebugStopProgram,
	cmMrDebugRestartProgram,
	cmMrDebugClearOutput,
	cmMrDebugFindNextCompilerError,
	cmMrTextMatchBraceOrParen,
	cmMrDebugGitChanges,

	cmMrMacroToggleRecording,

	cmMrHelpContents,
	cmMrHelpKeys,
	cmMrHelpDetailedIndex,
	cmMrHelpPreviousTopic,
	cmMrHelpPerformancePanel,
	cmMrHelpUpdate,
	cmMrHelpAbout,

	cmMrSetupEditSettings,
	cmMrSetupColorSetup,
	cmMrSetupKeyMapping,
	cmMrSetupFilenameExtensions,
	cmMrSetupCompilerProfiles,
	cmMrSetupPaths,
	cmMrSetupBackupsAutosave,
	cmMrSetupUserInterfaceSettings,
	cmMrSetupLiveLogs,

	cmMrColorWindowColors,
	cmMrColorMenuDialogColors,
	cmMrColorHelpColors,
	cmMrColorOtherColors,
	cmMrColorLoadTheme,
	cmMrColorSaveTheme,

	cmMrPreviewPrev,
	cmMrPreviewNext,

	cmMrSearchMultiFileSearch,
	cmMrSearchListFilesFromLastSearch,
	cmMrSearchMultiFileSearchReplace,
	cmMrEnsureUsableWorkWindow,
	cmMrDeferredActivateWindow,
	cmMrWindowTopologyChanged,
	cmMrFileSaveAll,
	cmMrFileRevert,
	cmMrDebugBuildCurrentFile,
	cmMrDebugFindPreviousCompilerError,
	cmMrBlockLoadFromDisk,
	cmMrEditToggleInsertMode,
	cmMrToggleFullscreen,
	cmMrFileOpenWorkspace,
	cmMrFileCompareApplyOriginalToCompare,
	cmMrFileCompareApplyCompareToOriginal,
	cmMrFileCompareNextChange,
	cmMrFileComparePreviousChange,
	cmMrTextReferences,
	cmMrTextRename,
	cmMrFileGetLast,
	cmMrTextToggleLineDrawing,
	cmMrTextToggleDoubleLines,
	cmMrTextLocalOutline,
	cmMrMacroDebuggerContinue,
	cmMrMacroDebuggerStep,
	cmMrMacroDebuggerStepOver,
	cmMrMacroDebuggerStepOut,
	cmMrMacroDebuggerStop,
	cmMrMacroDebuggerAddWatch,
	cmMrMacroDebuggerEraseWatch,
	cmMrMacroDebuggerRunHere,
	cmMrMacroDebuggerEvaluate,
	cmMrMacroDebuggerToggleBreakpointEnabled,
	cmMrMacroDebuggerToggleAllBreakpoints,
	cmMrMacroDebuggerClearAllBreakpoints = 106,
	cmMrDeferredWindowClose = 257,
	cmMrTextHexEditor = 107,
	cmMrEditorDocumentCommitted = 259,
	cmMrCoprocessorDialogResult,
	cmMrUpdateRestart,
	cmMrDebuggerEvaluate = 263,
	cmMrDebuggerContinue,
	cmMrDebuggerStep,
	cmMrDebuggerStepOver,
	cmMrDebuggerStepOut,
	cmMrDebuggerStop,
	cmMrDebuggerAddWatch,
	cmMrDebuggerEraseWatch,
	cmMrDebuggerRunHere,
	cmMrDebuggerToggleBreakpoint,
	cmMrDebuggerRebuildAndStart,
	cmMrDebuggerClearProgramTerminal = 108,
	cmMrRuntimeScheduleChanged = 275,
	cmMrWorkspaceAutosaveScheduled,
	cmMrDeferredUiQueued,
	cmMrMacroBrainStateChanged,
	cmMrDebuggerEditBreakpointAssert
};

static_assert(cmMrDebuggerStart <= 255, "Debugger start must fit TVision's command enablement set.");
static_assert(cmMrMacroDebuggerClearAllBreakpoints <= 255 && cmMrTextHexEditor <= 255 && cmMrDebuggerClearProgramTerminal <= 255,
              "Enabled application commands must fit TVision's command enablement set.");

#endif
