#ifndef MRCOMMANDS_HPP
#define MRCOMMANDS_HPP

#include <tvision/tv.h>

enum : ushort {
	cmMrFileOpen = 110,
	cmMrFileLoad,
	cmMrFileAcquire,
	cmMrFileOpenLiveLog,
	cmMrFileOpenJournal,
	cmMrFileSave,
	cmMrFileSaveAs,
	cmMrFileInformation,
	cmMrFileMerge,
	cmMrFilePrint,
	cmMrFileShellToDos,

	cmMrEditUndo,
	cmMrEditRedo,
	cmMrEditCutToBuffer,
	cmMrEditCopyToBuffer,
	cmMrEditAppendToBuffer,
	cmMrEditCutAndAppendToBuffer,
	cmMrEditPasteFromBuffer,
	cmMrEditRepeatCommand,

	cmMrWindowOpen,
	cmMrWindowClose,
	cmMrWindowSplit,
	cmMrWindowList,
	cmMrWindowNext,
	cmMrWindowPrevious,
	cmMrWindowAdjacent,
	cmMrWindowHide,
	cmMrWindowModifySize,
	cmMrWindowZoom,
	cmMrWindowMinimize,
	cmMrWindowRestore,
	cmMrWindowOrganize,
	cmMrWindowLink,
	cmMrWindowUnlink,
	cmMrWindowCascade,
	cmMrWindowTile,
	cmMrWindowSplitHorizontal,
	cmMrWindowSplitVertical,
	cmMrWindowNextDesktop,
	cmMrWindowPrevDesktop,
	cmMrWindowMoveToNextDesktop,
	cmMrWindowMoveToPrevDesktop,

	cmMrBlockCopy,
	cmMrBlockMove,
	cmMrBlockDelete,
	cmMrBlockSaveToDisk,
	cmMrBlockIndent,
	cmMrBlockUndent,
	cmMrBlockWindowCopy,
	cmMrBlockWindowMove,
	cmMrBlockMarkLines,
	cmMrBlockMarkColumns,
	cmMrBlockMarkStream,
	cmMrBlockToggleMarking,
	cmMrBlockToggleVisibility,
	cmMrBlockEndMarking,
	cmMrBlockTurnMarkingOff,
	cmMrBlockPersistent,

	cmMrSearchFindText,
	cmMrSearchReplace,
	cmMrSearchRepeatPrevious,
	cmMrSearchPushMarker,
	cmMrSearchGetMarker,
	cmMrSearchSetRandomAccessMark,
	cmMrSearchRetrieveRandomAccessMark,
	cmMrSearchGotoLineNumber,

	cmMrTextLayout,
	cmMrTextUpperCaseMenu,
	cmMrTextLowerCaseMenu,
	cmMrTextCenterLine,
	cmMrTextTimeDateStamp,
	cmMrTextReformatParagraph,
	cmMrTextFileCompare,
	cmMrTextUpperCasePlaceholder,
	cmMrTextLowerCasePlaceholder,

	cmMrOtherInstallationAndSetup,
	cmMrOtherMacroManager,
	cmMrOtherExecuteProgram,
	cmMrOtherStopProgram,
	cmMrOtherRestartProgram,
	cmMrOtherClearOutput,
	cmMrOtherFindNextCompilerError,
	cmMrOtherMatchBraceOrParen,
	cmMrOtherAsciiTable,

	cmMrMacroToggleRecording,

	cmMrHelpContents,
	cmMrHelpKeys,
	cmMrHelpDetailedIndex,
	cmMrHelpPreviousTopic,
	cmMrHelpPerformancePanel,
	cmMrHelpAbout,

	cmMrSetupEditSettings,
	cmMrSetupColorSetup,
	cmMrSetupKeyMapping,
	cmMrSetupLspSupport,
	cmMrSetupFilenameExtensions,
	cmMrSetupCompilerProfiles,
	cmMrSetupPaths,
	cmMrSetupBackupsAutosave,
	cmMrSetupSearchAndReplaceDefaults,
	cmMrSetupUserInterfaceSettings,
	cmMrSetupLiveLogs,

	cmMrColorWindowColors,
	cmMrColorMenuDialogColors,
	cmMrColorHelpColors,
	cmMrColorOtherColors,
	cmMrColorLoadTheme,
	cmMrColorSaveTheme,

	cmMrPreviewPrev,
	cmMrPreviewNext,

	cmMrSearchMultiFileSearch,
	cmMrSearchListFilesFromLastSearch,
	cmMrSearchMultiFileSearchReplace,
	cmMrOtherEmojiTable,
	cmMrEnsureUsableWorkWindow,
	cmMrDeferredActivateWindow,
	cmMrWindowTopologyChanged,
	cmMrFileSaveAll,
	cmMrFileRevert,
	cmMrOtherBuildCurrentFile,
	cmMrOtherFindPreviousCompilerError,
	cmMrBlockLoadFromDisk,
	cmMrEditToggleInsertMode,
	cmMrToggleFullscreen,
	cmMrFileOpenWorkspace,
	cmMrFileCompareApplyOriginalToCompare,
	cmMrFileCompareApplyCompareToOriginal,
	cmMrFileCompareNextChange,
	cmMrFileComparePreviousChange,
	cmMrOtherLspDefinition,
	cmMrOtherLspReferences,
	cmMrOtherLspHover,
	cmMrOtherLspComplete,
	cmMrOtherLspDocumentSymbols,
	cmMrOtherLspSignatureHelp,
	cmMrOtherLspStatus,
	cmMrOtherLspResults,
	cmMrOtherLspCodeActions
};

#endif
