#include "MRKeymapActionCatalog.hpp"

#include <algorithm>
#include <array>

namespace {
constexpr MRKeymapActionDefinition mrmac(std::string_view id, std::string_view label) noexcept {
	return {id, MRKeymapActionOrigin::MRMAC, label, label};
}

constexpr MRKeymapActionDefinition mr(std::string_view id, std::string_view label) noexcept {
	return {id, MRKeymapActionOrigin::MR, label, label};
}

constexpr std::array catalogDefinitions{
    mrmac("MRMAC_CURSOR_LEFT", "Cursor left"),
    mrmac("MRMAC_CURSOR_RIGHT", "Cursor right"),
    mrmac("MRMAC_CURSOR_UP", "Cursor up"),
    mrmac("MRMAC_CURSOR_DOWN", "Cursor down"),
    mrmac("MRMAC_CURSOR_HOME", "Cursor to home"),
    mrmac("MRMAC_CURSOR_END_OF_LINE", "Cursor to end of line"),
    mrmac("MRMAC_VIEW_PAGE_UP", "Display page up"),
    mrmac("MRMAC_VIEW_PAGE_DOWN", "Display page down"),
    mrmac("MRMAC_CURSOR_TOP_OF_FILE", "To top of the file"),
    mrmac("MRMAC_CURSOR_BOTTOM_OF_FILE", "To bottom of the file"),
    mrmac("MRMAC_CURSOR_NEXT_PAGE_BREAK", "Cursor to next page break"),
    mrmac("MRMAC_CURSOR_PREV_PAGE_BREAK", "Cursor to last page break"),
    mrmac("MRMAC_CURSOR_WORD_LEFT", "Cursor word left"),
    mrmac("MRMAC_CURSOR_WORD_RIGHT", "Cursor word right"),
    mrmac("MRMAC_CURSOR_TOP_OF_WINDOW", "Top of window"),
    mrmac("MRMAC_CURSOR_BOTTOM_OF_WINDOW", "Bottom of window"),
    mrmac("MRMAC_VIEW_SCROLL_UP", "Scroll window up"),
    mrmac("MRMAC_VIEW_SCROLL_DOWN", "Scroll window down"),
    mrmac("MRMAC_CURSOR_START_OF_BLOCK", "Cursor to start of block"),
    mrmac("MRMAC_CURSOR_END_OF_BLOCK", "Cursor to end of block"),
    mrmac("MRMAC_CURSOR_GOTO_LINE", "Move cursor to line num"),
    mrmac("MRMAC_CURSOR_INDENT", "Indent"),
    mrmac("MRMAC_CURSOR_TAB_RIGHT", "Tab right"),
    mrmac("MRMAC_CURSOR_TAB_LEFT", "Tab left"),
    mrmac("MRMAC_CURSOR_UNDENT", "Undent"),
    mrmac("MRMAC_MARK_PUSH_POSITION", "Mark position on stack"),
    mrmac("MRMAC_MARK_POP_POSITION", "Get position from stack"),
    mrmac("MRMAC_MARK_SET_RANDOM_ACCESS", "Set a random access mark"),
    mrmac("MRMAC_VIEW_CENTER_LINE", "Center line on screen"),
    mrmac("MRMAC_MARK_GET_RANDOM_ACCESS", "Get random access mark"),
    mrmac("MRMAC_DELETE_TO_EOL", "Delete to end of line"),
    mrmac("MRMAC_DELETE_FORWARD_CHAR_OR_BLOCK", "Del character (or block)"),
    mrmac("MRMAC_DELETE_FORWARD_WORD", "Delete word forward"),
    mrmac("MRMAC_DELETE_BACKWARD_CHAR", "Back space"),
    mrmac("MRMAC_DELETE_BACKWARD_WORD", "Backspace a whole word"),
    mrmac("MRMAC_DELETE_LINE", "Delete line"),
    mrmac("MRMAC_DELETE_BACKWARD_TO_HOME", "Backspace to home"),
    mrmac("MRMAC_UNDO", "Undo"),
    mrmac("MRMAC_REDO_LAST_UNDO", "Undo your last undo"),
    mrmac("MRMAC_SEARCH_FORWARD", "Search"),
    mrmac("MRMAC_SEARCH_REPLACE", "Search and replace"),
    mrmac("MRMAC_SEARCH_REPEAT_LAST", "Repeat last Search/Replace"),
    mrmac("MRMAC_SEARCH_MULTI_FILE", "Multi file search"),
    mrmac("MRMAC_SEARCH_LIST_MATCHED_FILES", "List matched files"),
    mrmac("MRMAC_BLOCK_COPY_TO_CLIPBOARD", "Copy to MS Windows"),
    mrmac("MRMAC_BLOCK_PASTE_FROM_CLIPBOARD", "Paste from MS Windows"),
    mrmac("MRMAC_BLOCK_MARK_STREAM", "Mark a stream block"),
    mrmac("MRMAC_BLOCK_SET_BEGIN", "Set block begin"),
    mrmac("MRMAC_BLOCK_SET_END", "Set block end"),
    mrmac("MRMAC_BLOCK_SET_COLUMN_BEGIN", "Set column block begin"),
    mrmac("MRMAC_BLOCK_MARK_WORD_RIGHT", "Mark word right"),
    mrmac("MRMAC_BLOCK_CLEAR", "Turn block mark off"),
    mrmac("MRMAC_BLOCK_TOGGLE_VISIBILITY", "Hide/show block mark"),
    mrmac("MRMAC_BLOCK_UNDENT", "Undent block"),
    mrmac("MRMAC_BLOCK_INDENT", "Indent block"),
    mrmac("MRMAC_BLOCK_COPY", "Copy the marked block"),
    mrmac("MRMAC_BLOCK_MOVE", "Move marked block"),
    mrmac("MRMAC_BLOCK_DELETE", "Delete marked block"),
    mrmac("MRMAC_BLOCK_COPY_INTERWINDOW", "Interwindow block copy"),
    mrmac("MRMAC_BLOCK_MOVE_INTERWINDOW", "Interwindow block move"),
    mrmac("MRMAC_BLOCK_MOVE_TO_BUFFER", "Move block to buffer"),
    mrmac("MRMAC_BLOCK_APPEND_TO_BUFFER", "Append block to buffer"),
    mrmac("MRMAC_BLOCK_CUT_APPEND_TO_BUFFER", "Cut and Append Block"),
    mrmac("MRMAC_BLOCK_COPY_FROM_BUFFER", "Copy block from buffer"),
    mrmac("MRMAC_BLOCK_EXTEND_BY_MOTION", "Shift cursor block mark"),
    mrmac("MRMAC_FILE_SAVE", "Save file"),
    mr("MR_BLOCK_MARK_LINES", "Mark line block"),
    mr("MR_BLOCK_TOGGLE_MARKING", "Toggle line block marking"),
    mr("MR_BLOCK_TOGGLE_VISIBILITY", "Hide/show block mark"),
    mr("MR_FILE_SAVE_ALL", "Save all dirty files"),
    mr("MR_FILE_REVERT", "Revert file"),
    mr("MR_SAVE_BLOCK_TO_FILE", "Save block to file"),
    mr("MR_LOAD_BLOCK_FROM_FILE", "Load block from file"),
    mr("MR_EDIT_MARK_ALL", "Mark all as line block"),
    mr("MR_EDIT_TOGGLE_INSERT_MODE", "Toggle insert mode"),
    mr("MR_TEXT_TOGGLE_LINE_DRAWING", "Toggle line drawing"),
    mr("MR_TEXT_TOGGLE_DOUBLE_LINES", "Toggle double lines"),
    mr("MR_TEXT_CENTER_LINE", "Center current line"),
    mr("MR_TEXT_REFORMAT_PARAGRAPH", "Reformat paragraph"),
    mr("MR_TEXT_REFORMAT_DOCUMENT", "Reformat document"),
    mr("PRETTIFY_BLOCK_OR_FILE", "Re-format code"),
    mr("MR_TEXT_FILE_COMPARE", "File compare"),
    mr("MR_TOGGLE_FORMAT_RULER", "Toggle format ruler"),
    mr("MR_TOGGLE_WORD_WRAP", "Toggle word wrap"),
    mr("MR_SET_LEFT_MARGIN", "Set left margin"),
    mr("MR_SET_RIGHT_MARGIN", "Set right margin"),
    mr("MR_JUSTIFY_PARAGRAPH", "Justify paragraph"),
    mr("MR_SORT_COLUMN_BLOCK_TOGGLE", "Sort marked column block"),
    mr("MR_FILE_FORCE_SAVE", "Force save"),
    mr("MR_EXIT_DIRTY_SAVE_ALL", "Exit with save-all dialog"),
    mr("MR_WINDOW_OPEN", "Open window"),
    mr("MR_WINDOW_NEXT", "Next window"),
    mr("MR_WINDOW_PREVIOUS", "Previous window"),
    mr("MR_WINDOW_LIST", "Window list"),
    mr("MR_WINDOW_CLOSE", "Close window"),
    mr("MR_WINDOW_ZOOM", "Zoom window"),
    mr("MR_WINDOW_CASCADE", "Cascade windows"),
    mr("MR_WINDOW_TILE", "Tile windows"),
    mr("MR_WINDOW_SPLIT_VERTICAL", "Split window vertically"),
    mr("MR_WINDOW_SPLIT_HORIZONTAL", "Split window horizontally"),
    mr("MR_DESKTOP_VIEWPORT_LEFT", "Move viewport left"),
    mr("MR_DESKTOP_VIEWPORT_RIGHT", "Move viewport right"),
    mr("MR_DESKTOP_MOVE_WINDOW_LEFT", "Move window to left desktop"),
    mr("MR_DESKTOP_MOVE_WINDOW_RIGHT", "Move window to right desktop"),
    mr("MR_BUILD_CURRENT_FILE", "Build current file"),
    mr("MR_DEBUGGER_START", "Debug current file"),
    mr("MR_DEBUGGER_EVALUATE", "Debugger evaluate"),
    mr("MR_DEBUGGER_CONTINUE_PAUSE", "Debugger continue / pause"),
    mr("MR_DEBUGGER_RUN_HERE", "Debugger run here"),
    mr("MR_DEBUGGER_ADD_WATCH", "Debugger add watch"),
    mr("MR_DEBUGGER_ERASE_WATCH", "Debugger erase watch"),
    mr("MR_DEBUGGER_STOP_RESET", "Debugger stop / reset"),
    mr("MR_DEBUGGER_TOGGLE_BREAKPOINT", "Debugger toggle breakpoint"),
    mr("MR_DEBUGGER_STEP_INTO", "Debugger step into"),
    mr("MR_DEBUGGER_STEP", "Debugger step"),
    mr("MR_DEBUGGER_STEP_OUT", "Debugger step out"),
    mr("MR_DEBUGGER_CLEAR_PROGRAM_TERMINAL", "Clear Program Terminal"),
    mr("MR_MACRO_DEBUGGER_TOGGLE_BREAKPOINT_ENABLED", "Macro debugger enable / disable breakpoint"),
    mr("MR_MACRO_DEBUGGER_TOGGLE_ALL_BREAKPOINTS", "Macro debugger enable / disable all breakpoints"),
    mr("MR_MACRO_DEBUGGER_CLEAR_ALL_BREAKPOINTS", "Macro debugger clear all breakpoints"),
    mr("MR_SEARCH_RESULTS_NEXT", "Next search result"),
    mr("MR_SEARCH_MULTI_FILE_REPLACE", "Multi file search and replace"),
    mr("MR_COMPILER_PROBLEMS_NEXT", "Next compiler problem"),
    mr("MR_COMPILER_PROBLEMS_PREVIOUS", "Previous compiler problem"),
    mr("MR_MATCH_PARENTHESIS", "Match parenthesis"),
    mr("MR_FIND_REFERENCES", "References"),
    mr("MR_RENAME", "Rename"),
    mr("MR_SNIPPET_PLACEHOLDER_NEXT", "Snippet next placeholder"),
    mr("MR_SNIPPET_PLACEHOLDER_PREVIOUS", "Snippet previous placeholder"),
    mr("MR_MACRO_TOGGLE_RECORDING", "Toggle macro recording"),
    mr("MR_SETUP_EDIT_SETTINGS", "Setup edit settings"),
    mr("MR_SETUP_COLOR", "Setup colors"),
    mr("MR_SETUP_KEYMAP", "Setup keymap"),
    mr("MR_SETUP_FILENAME_EXTENSIONS", "Setup filename extensions"),
    mr("MR_SETUP_COMPILER_PROFILES", "Setup compiler profiles"),
    mr("MR_SETUP_PATHS", "Setup paths"),
    mr("MR_SETUP_BACKUPS_AUTOSAVE", "Setup backups / autosave"),
    mr("MR_SETUP_USER_INTERFACE", "Setup user interface"),
    mr("MR_SETUP_LIVE_LOGS", "Setup live logs"),
};
} // namespace

const MRKeymapActionDefinition *MRKeymapActionCatalog::findById(std::string_view id) noexcept {
	for (const MRKeymapActionDefinition &definition : catalogDefinitions)
		if (definition.id == id) return &definition;
	return nullptr;
}

bool MRKeymapActionCatalog::contains(std::string_view id) noexcept {
	return findById(id) != nullptr;
}

std::span<const MRKeymapActionDefinition> MRKeymapActionCatalog::definitions() noexcept {
	return catalogDefinitions;
}
